services:
  migration-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration-service
    ports:
      - "8082:8082"
    environment:
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:17.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/data/db
    networks:
      - app-network
    restart: always
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge